# .github/workflows/main.yml
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Fix Git safe directory
        run: git config --global --add safe.directory /github/workspace
      - name: checkout
        uses: actions/checkout@v2
      - name: Disable Jekyll
        run: touch public/.nojekyll
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public