name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive  # make sure Kodama theme is cloned

      - name: Install Zola
        run: |
          curl -sSLf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install zola

      - name: Build site
        run: zola build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages